add_newline = true

# [battery]
#full_symbol = "🔋"
#charging_symbol = "⚡️"
#discharging_symbol = "💀"

#[[battery.display]]
#threshold = 10
#style = "bold red"

#[[battery.display]]
#threshold = 60
#style = "bold yellow"

#[[battery.display]]
#threshold = 100
#style = "bold green"

[character]
success_symbol = "[➜](bold green) "
error_symbol = "[✗](bold red) "

[cmd_duration]
min_time = 500
format = "tooks [$duration](bold yellow)"

[directory]
truncation_length = 6
truncate_to_repo = true
style = "bold green"
disabled = false

[git_branch]
symbol = "🌱 "
truncation_length = 50
truncation_symbol = "..."
style = "bold purple"
disabled = false

[git_commit]
commit_hash_length = 4
tag_symbol = "🔖 "

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '
style = "bold yellow"
disabled = false

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"
disabled  = false

[hostname]
ssh_only = true
format = "[$ssh_symbol](bold blue) on [$hostname](bold red) "
# trim_at = ".companyname.com"
disabled = false

# [jobs]
# symbol = "+ "
# threshold = 1

[line_break]
disabled = false

[python]
symbol = "🐍 "
pyenv_version_name = false
pyenv_prefix = "pyenv"
style = "bold yellow"
disabled = false

[username]
style_root = "bold red"
style_user = "bold yellow"
show_always = false
disabled = false

[helm]
format = "via [⎈ $version](bold white) "

[kubernetes]
# format = 'on [⛵ ($user on )($cluster in )$context \($namespace\)](dimmed green) '
style	= "cyan bold"
disabled = false

[kubernetes.context_aliases]
"dev.local.cluster.k8s" = "dev"
# ".*/openshift-cluster/.*" = "openshift"
# "gke_.*_(?P<var_cluster>[\\w-]+)" = "gke-$var_cluster"

# [custom.foo]
# command = "curl wttr.in/cambridge"
# detect_files = ["foo"] # can specify filters but wildcards are not supported
# when = """ test "$HOME" = "$PWD" """
